# -*- coding: utf-8 -*-
"""Matplotlib.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NvKe4oiV0GKQmwN-hPNIfqQT9yF1-5S3

**Matplotlib**

Matplotlib is a low level graph plotting library in python that serves as a visualization utility.

Matplotlib was created by John D. Hunter.

Matplotlib is open source and we can use it freely.

Matplotlib is mostly written in python, a few segments are written in C, Objective-C and Javascript for Platform compatibility.
"""

!pip install matplotlib

import matplotlib
print(matplotlib.__version__)

import matplotlib.pyplot as plt
import numpy as np
xpoints = np.array([0,6])
ypoints= np.array([0,250])

plt.plot(xpoints,ypoints)
plt.show()

xpoints = np.array([1,8,7])
ypoints= np.array([3,10,8])

plt.plot(xpoints,ypoints)
plt.show()

xpoints = np.array([1,8])
ypoints= np.array([3,10])

plt.plot(xpoints,ypoints,'o')#ring
plt.show()

xpoints = np.array([1,2,6,8])
ypoints= np.array([3,8,1,10])

plt.plot(xpoints,ypoints)
plt.show()

ypoints= np.array([3,8,1,10,5,7])

plt.plot(ypoints)#0,...n
plt.show()

ypoints= np.array([3,8,1,10,5,7])
plt.plot(ypoints,marker= 'o')#0,...n
plt.show()

ypoints= np.array([3,8,1,10,5,7])
plt.plot(ypoints,marker= '*')#0,...n
plt.show()

ypoints= np.array([3,8,1,10,5,7])
plt.plot(ypoints,marker= '+')#0,...n
plt.show()

"""'o'-circle

'*' -star

'.'-point

','-pixcel

'+'-plus
"""

ypoints= np.array([3,8,1,10,5,7])
plt.plot(ypoints,marker= '2')#0,...n#tri up
plt.show()

ypoints= np.array([3,8,1,10,5,7])
plt.plot(ypoints,marker= '1')#0,...n#tridown
plt.show()

ypoints= np.array([3,8,1,10,5,7])
plt.plot(ypoints,marker= '3')#0,...n#trileft
plt.show()

ypoints= np.array([3,8,1,10,5,7])
plt.plot(ypoints,marker= '4')#0,...n#triright
plt.show()

ypoints= np.array([3,8,1,10,5,7])
plt.plot(ypoints,marker= '+',ms=15)#0,...n
plt.show()

ypoints= np.array([3,8,1,10,5,7])
plt.plot(ypoints,marker= 'o',ms=15,mec='y')#marker edge color-mec
plt.show()

ypoints= np.array([3,8,1,10,5,7])
plt.plot(ypoints,marker= 'o',ms=15,mec='r',mfc='g')#marker face colour-mfc
plt.show()

ypoints= np.array([3,8,1,10,5,7])
plt.plot(ypoints,marker= 'o',ms=15,mec='#4CAF50',mfc='red')#marker face colour-mfc
plt.show()

#line style
ypoints= np.array([3,8,1,10,5,7])
plt.plot(ypoints,linestyle = 'dotted')
plt.show()

ypoints= np.array([3,8,1,10,5,7])
plt.plot(ypoints,ls = "--")
plt.show()

"""#linestyle

'_'-'solid'

':'-'dotted'

'--'-'dashed'

'-.'-'dashdot'
"""

ypoints= np.array([3,8,1,10,5,7])
plt.plot(ypoints,ls='dashdot')
plt.show()

ypoints= np.array([3,8,1,10,5,7])
plt.plot(ypoints,ls='dashdot',color = 'g')
plt.show()

ypoints= np.array([3,8,1,10,5,7])
plt.plot(ypoints,c= 'blue')
plt.show()

ypoints= np.array([3,8,1,10,5,7])
plt.plot(ypoints,lw = '8')
plt.show()

y1= np.array([3,8,1,10,5,7])
y2= np.array([6,2,7,11,8,12])#x = 0,1,2,3,...n
plt.plot(y1,c='r')
plt.plot(y2)
plt.show()

x1=np.array([4,8,9,7])
x2=np.array([3,5,8,7])
y1= np.array([3,8,1,10])
y2= np.array([6,2,7,11])#x = 0,1,2,3,...n
plt.plot(x1,y1,c='r')
plt.plot(x2,y2)
plt.show()

y1= np.array([3,8,1,10,5,7])
y2= np.array([6,2,7,11,8,12])
plt.plot(y1)
plt.plot(y2)
plt.xlabel('x-axis')
plt.ylabel('y-axis')
plt.show()

y1= np.array([3,8,1,10,5,7])
y2= np.array([6,2,7,11,8,12])
plt.plot(y1)
plt.plot(y2)
plt.xlabel('x-axis')
plt.ylabel('y-axis')
plt.title('graph')
plt.show()

x = np.array([80,85,90,95,100,105,110,115,120,125])
y=np.array([240,250,260,270,280,290,300,310,320,330])
font1 = {'family':'serif','color':'blue','size':20}
font2 = {'family':'serif','color':'red','size':15}
plt.title("graph",fontdict = font2)
plt.ylabel("ylabel",fontdict = font1)
plt.xlabel("xlabel",fontdict = font1)
plt.plot(x,y)
plt.show()

x = np.array([80,85,90,95,100,105,110,115,120,125])
y=np.array([240,250,260,270,280,290,300,310,320,330])
font1 = {'family':'serif','color':'blue','size':20}
font2 = {'family':'serif','color':'red','size':15}
plt.title("graph",fontdict = font2,loc ='Left')
plt.ylabel("ylabel",fontdict = font1)
plt.xlabel("xlabel",fontdict = font1)
plt.plot(x,y)
plt.show()

x = np.array([80,85,90,95,100,105,110,115,120,125])
y=np.array([240,250,260,270,280,290,300,310,320,330])
font1 = {'family':'serif','color':'blue','size':20}
font2 = {'family':'serif','color':'red','size':15}
plt.title("graph",fontdict = font2)
plt.ylabel("ylabel",fontdict = font1)
plt.xlabel("xlabel",fontdict = font1)
plt.plot(x,y)
plt.grid()
plt.show()

x = np.array([80,85,90,95,100,105,110,115,120,125])
y=np.array([240,250,260,270,280,290,300,310,320,330])
font1 = {'family':'serif','color':'blue','size':20}
font2 = {'family':'serif','color':'red','size':15}
plt.title("graph",fontdict = font2)
plt.ylabel("ylabel",fontdict = font1)
plt.xlabel("xlabel",fontdict = font1)
plt.plot(x,y)
plt.grid(axis = 'x')
plt.show()

x = np.array([80,85,90,95,100,105,110,115,120,125])
y=np.array([240,250,260,270,280,290,300,310,320,330])
font1 = {'family':'serif','color':'blue','size':20}
font2 = {'family':'serif','color':'red','size':15}
plt.title("graph",fontdict = font2)
plt.ylabel("ylabel",fontdict = font1)
plt.xlabel("xlabel",fontdict = font1)
plt.plot(x,y)
plt.grid(axis = 'y')
plt.show()

x = np.array([80,85,90,95,100,105,110,115,120,125])
y=np.array([240,250,260,270,280,290,300,310,320,330])
font1 = {'family':'serif','color':'blue','size':20}
font2 = {'family':'serif','color':'red','size':15}
plt.title("graph",fontdict = font2)
plt.ylabel("ylabel",fontdict = font1)
plt.xlabel("xlabel",fontdict = font1)
plt.plot(x,y)
plt.grid(color='orange',ls=':',lw=5)
plt.show()

#subplot
#plot-1
x = np.array([0,1,2,3])
y= np.array([3,8,1,10])
plt.subplot(1,2,1)
plt.plot(x,y)
#plot-2
x = np.array([0,1,2,3])
y= np.array([10,20,30,40])
plt.subplot(1,2,2)
plt.plot(x,y)
plt.show

#subplot
#plot-1
x = np.array([0,1,2,3])
y= np.array([3,8,1,10])
plt.subplot(2,1,1)
plt.plot(x,y)
#plot-2
x = np.array([0,1,2,3])
y= np.array([10,20,30,40])
plt.subplot(2,1,2)
plt.plot(x,y)
plt.show

#subplot
#plot-1
x = np.array([0,1,2,3])
y= np.array([3,8,1,10])
plt.subplot(2,3,1)
plt.plot(x,y)
#plot-2
x = np.array([0,1,2,3])
y= np.array([10,20,30,40])
plt.subplot(2,3,2)
plt.plot(x,y)

#plot-3
x = np.array([0,1,2,3])
y= np.array([3,8,1,10])
plt.subplot(2,3,3)
plt.plot(x,y)
#plot-4
x = np.array([0,1,2,3])
y= np.array([10,20,30,40])
plt.subplot(2,3,4)
plt.plot(x,y)
#plot-5
x = np.array([0,1,2,3])
y= np.array([3,8,1,10])
plt.subplot(2,3,5)
plt.plot(x,y)
#plot-6
x = np.array([0,1,2,3])
y= np.array([10,20,30,40])
plt.subplot(2,3,6)
plt.plot(x,y)
plt.show

#subplot
#plot-1
x = np.array([0,1,2,3])
y= np.array([3,8,1,10])
plt.subplot(1,2,1)
plt.plot(x,y)
plt.title('sales')
#plot-2
x = np.array([0,1,2,3])
y= np.array([10,20,30,40])
plt.subplot(1,2,2)
plt.plot(x,y)
plt.title('income')
plt.show

#subplot
#plot-1
x = np.array([0,1,2,3])
y= np.array([3,8,1,10])
plt.subplot(1,2,1)
plt.plot(x,y)
plt.title('sales',loc='left')
#plot-2
x = np.array([0,1,2,3])
y= np.array([10,20,30,40])
plt.subplot(1,2,2)
plt.plot(x,y)
plt.title('income',loc = 'left')
plt.suptitle('my shop')
plt.show

#scatter plot
x = np.array([5,7,8,2,6,7])
y = np.array([88,99,77,66,55,44])
plt.scatter(x,y)
plt.show()

#scatter plot
x1 = np.array([5,7,8,2,6,7])
y1 = np.array([88,99,77,66,55,44])
x2 = np.array([2,4,8,2,10,7])
y2 = np.array([10,35,85,60,45,44])
plt.scatter(x1,y1)
plt.scatter(x2,y2)
plt.show()

#scatter plot
x1 = np.array([5,7,8,2,6,7])
y1 = np.array([88,99,77,66,55,44])
x2 = np.array([2,4,8,2,10,7])
y2 = np.array([10,35,85,60,45,44])
plt.scatter(x1,y1,color='green')
plt.scatter(x2,y2,color='red')

plt.show()

#scatter plot
x1 = np.array([5,7,8,2,6,7])
y1 = np.array([88,99,77,66,55,44])

colors = np.array(["red","blue","orange","hotpink","green","yellow"])
plt.scatter(x1,y1,color=colors)

plt.show()

#scatter plot
x1 = np.array([5,7,8,2,6,7])
y1 = np.array([88,99,77,66,55,44])

colors = np.array([0,10,20,30,40,50])
size = np.array([10,20,30,40,50,60])
plt.scatter(x1,y1,c=colors,cmap = 'viridis',s = size)
plt.colorbar()

plt.show()

#scatter plot
x1 = np.array([5,7,8,2,6,7])
y1 = np.array([88,99,77,66,55,44])

colors = np.array([0,10,20,30,40,50])
size = np.array([60,70,80,90,100,110])
plt.scatter(x1,y1,c=colors,cmap = 'viridis',s = size,alpha = 0.5)
plt.colorbar()

plt.show()

x= np.array(["a","b","c","d"])
y = np.array([3,8,1,10])
plt.bar(x,y)
plt.show()

x= ["apples","banana"]
y = [400,350]
plt.bar(x,y)
plt.show()

x= ["apples","banana"]
y = [400,350]
plt.barh(x,y)
plt.show()

x= ["apples","banana"]
y = [400,350]
plt.bar(x,y,color= 'green',width = 0.5)
plt.show()

x= ["apples","banana"]
y = [400,350]
plt.barh(x,y,color= 'green',height = 0.5)#0.8
plt.show()

x = np.random.normal(170,10,250)
print(x)

x = np.random.normal(170,10,250)
plt.hist(x)
plt.show()

y = np.array([35,25,25,15])
plt.pie(y)
plt.show()

y = np.array([35,25,25,15])
mylabels = ["APPLES","BANANA","DATES","CHERRIES"]
plt.pie(y,labels =mylabels )
plt.show()

y = np.array([35,25,25,15])
mylabels = ["APPLES","BANANA","DATES","CHERRIES"]
plt.pie(y,labels =mylabels ,startangle=90)
plt.show()

y = np.array([35,25,25,15])
mylabels = ["APPLES","BANANA","DATES","CHERRIES"]
myexplode = [0.2,0,0,0]
plt.pie(y,labels =mylabels,explode = myexplode )
plt.show()

y = np.array([35,25,25,15])
mylabels = ["APPLES","BANANA","DATES","CHERRIES"]
myexplode = [0.2,0,0,0]
plt.pie(y,labels =mylabels,explode = myexplode ,shadow = True)
plt.show()

y = np.array([35,25,25,15])
mylabels = ["APPLES","BANANA","DATES","CHERRIES"]
mycolor = ["black","red","green","orange"]
myexplode = [0.2,0,0,0]
plt.pie(y,labels =mylabels,explode = myexplode ,shadow = True,colors =mycolor )
plt.show()

y = np.array([35,25,25,15])
mylabels = ["APPLES","BANANA","DATES","CHERRIES"]
mycolor = ["black","red","green","orange"]
myexplode = [0.2,0,0,0]
plt.pie(y,labels =mylabels,explode = myexplode ,shadow = True,colors =mycolor )
plt.legend()
plt.show()

y = np.array([35,25,25,15])
mylabels = ["APPLES","BANANA","DATES","CHERRIES"]
mycolor = ["black","red","green","orange"]
myexplode = [0.2,0,0,0]
plt.pie(y,labels =mylabels,explode = myexplode ,shadow = True,colors =mycolor )
plt.legend(title = 'four fruits')
plt.show()