# -*- coding: utf-8 -*-
"""numpy-2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mSAW6STymZCL7gPosmjuraw79iTJP94u
"""

#shape
import numpy as np
arr = np.array([[1,2,3,4,51],[1,2,3,4,5]])
print(arr)
print(arr.shape)

arr = np.array([1,2,3,4,5],ndmin = 5)

print(arr)
print(arr.shape)

#reshape
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

newarr = arr.reshape(4,3)
print(newarr)

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(2,3,2)
print(newarr)

arr = np.array([[1,2,3,4,5],[11,22,33,44,55]])
new =arr.reshape(-1)
print(new)

arr = np.array([1,2,3,4,5,6])

for x in arr:
  print(x)

arr = np.array([[1,2,3,4,5],[11,22,33,44,55]])
for x in arr:
  for y in x:
    print(y)

arr = np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[11,12,13,14,15],[16,17,18,19,20]]])
for x in arr:
  for y in x:
    for z in y:
      print (z)

arr = np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[11,12,13,14,15],[16,17,18,19,20]]])
for x in np.nditer(arr):
  print(x)

arr = np.array([1,2,3,4,5,6])

for x in np.nditer(arr,flags = ['buffered'],op_dtypes=['S']):
  print(x.dtype)

arr = np.array([1,2,3,4,5,6])

for idx,x in np.ndenumerate(arr):
  print(idx,x)

arr = np.array([[1,2,3,4,5,6],[11,22,33,44,55,66]])
for idx,x in np.ndenumerate(arr):
  print(idx,x)

#join

arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([11,12,13,14,15,16])


arr = np.concatenate((arr1,arr2))

print(arr)

arr1 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr2 = np.array([[11,22,33,44,55],[66,77,88,99,100]])


arr = np.concatenate((arr1,arr2),axis = 1)
print(arr1)
print(arr2)
print(arr)

arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([11,12,13,14,15,16])

arr = np.hstack((arr1,arr2))

print(arr)

arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([11,12,13,14,15,16])

arr = np.vstack((arr1,arr2))

print(arr)

arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([11,12,13,14,15,16])

arr = np.dstack((arr1,arr2))

print(arr)

arr1 = np.array([1,2,3,4,5,6])

new = np.array_split(arr1,3)
print(new)

arr1 = np.array([1,2,3,4,5,6])

new = np.array_split(arr1,4)
print(new)

print(new[0])
print(new[1])
print(new[2])

arr1 = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])

new = np.hsplit(arr1,3)
print(new)

for i in new:
  print(i)

arr1 = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])

new = np.vsplit(arr1,2)
print(new)

for i in new:
  print(i)

arr1 = np.array([1,2,3,4,5,6,7,8,9])

x = np.where(arr1 == 5)

print(x)

arr1 = np.array([1,2,3,4,5,6,7,8,9])

x = np.where(arr1%2 == 0)

print(x)

arr1 = np.array([1,2,3,4,5,6,7,8,9])

x = np.where(arr1%2 == 1)

print(x)

arr1 = np.array([1,2,3,4,5,6,7,8,9])

x = np.searchsorted(arr1,5)

print(x)

arr1 = np.array([1,2,3,4,5,6,7,8,9])

x = np.searchsorted(arr1,5,side = 'right')

print(x)

arr1 = np.array([1,2,3,4,5,6,7,8,9])

x = np.searchsorted(arr1,[2,4,5])

print(x)

arr1 = np.array([4,9,8,2,3,1,6])
print(np.sort(arr1))

arr = np.array(["chery","banana","apple"])
print(np.sort(arr))

arr = np.array([[3,2,4],[5,0,1]])
print(np.sort(arr))

arr = np.array([41,42,43,45,46,48])

x = [True,False,True,False,True,False]

newarr = arr[x]


print(newarr)

arr = np.array([41,42,43,45,46,48])

filter_arr = []

for elem in arr:

  if elem >43:
    filter_arr.append(True)
  else:
    filter_arr.append(False)


newarr = arr[filter_arr]

print(newarr)
print(filter_arr)

arr = np.array([41,42,43,45,46,48])
filter_arr = arr > 43
newarr = arr[filter_arr]

print(newarr)
print(filter_arr)

arr = np.array([41,42,43,45,46,48])

filter_arr = []

for elem in arr:

  if elem %2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)


newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

arr = np.array([41,42,43,45,46,48])
filter_arr = arr %2 == 0
newarr = arr[filter_arr]

print(newarr)
print(filter_arr)

from numpy import random
x = random.randint(100)
print(x)

x = random.rand()
print(x)

x = random.randint(100,size = (5))
print(x)

x = random.rand(5)
print(x)

x = random.randint(100,size = (2,5))
print(x)

x = random.rand(2,5)
print(x)

x = random.choice([3,4,5,6,7,8])

print(x)

x = random.choice([3,4,5,6,7,8],size = (3,5))

print(x)

