# -*- coding: utf-8 -*-
"""Pandas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jw7dQ_7TYrIOLN1JuXCSuiShEvXIVdSg
"""

! pip install pandas

import pandas as pd
print(pd.__version__)

a = [1,2,3]
var = pd.Series(a)
print(var)

print(var[0])

a = [1,2,3]
var = pd.Series(a,index = ["x","y","z"])
print(var)

print(var["z"])

calories = {"day1":420.3,"day2":360,"day3":350.3}

var = pd.Series(calories)
print(var)

print(var["day3"])

data = {
        "calories":[420,350,390],
        "duration":[50,40,45]
        }

df = pd.DataFrame(data)

print(df)

print(df.loc[0])

print(df.loc[[0,1]])

data = {
        "calories":[420,350,390],
        "duration":[50,40,45]
        }

df = pd.DataFrame(data,index = ["x","y","z"])

print(df)

print(df.loc["y"])

df = pd.read_csv('/content/data.csv')
print(df.to_string())

print(df)

df.head()

df.tail()

file_path = '/content/sample_data/anscombe.json'
df = pd.read_json(file_path)
print(df.head())

#empty cell ---values 20,30 --remove 0.2% ---95%
#data wrongformat
#wrong data
#duplicates

file_path = '/content/Data of Wrong .csv'
df = pd.read_csv(file_path,sep =",")
print(df.head())

print(df.to_string())

df1 = df.copy()
print(df1)

#remove null values
new_df = df1.dropna()
print(new_df.to_string())

print(df1.to_string())

print(new_df.to_string())

#remove null values
df1.dropna(inplace = True)
print(df1.to_string())

df2 = df.copy()
print(df2.to_string())

df2.fillna(130,inplace = True)
print(df2.to_string())

df3 = df.copy()

print(df3.to_string())

df3["Calories"].fillna(130,inplace = True)
print(df3.to_string())

