# -*- coding: utf-8 -*-
"""Python class day -3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17CTVABLVeH2OIOCdo_JeL5uPbYGmqmFi
"""



"""#operators

Arithmetic operators(+,-,*,/,%,**,//)

Assignment operators(=,+=,-=,*=,/=,%=,//=,**=,&=,|=,^=,>>=,<<=)

Comparison operators(==,!=,>,<,>=,<=)

Logical operators(and ,or,not)

Identity operators(is ,is not)

Membership operators(in ,not in)

Bitwise operators(& -AND,|-OR,^-XOR,~-NOT,<< -Zero fill left shift,>>-Signed right shift)

#Python I/O

input()

raw_input()


#import

import math-ceil,floor,sqrt,pi

#Namespace

#-single
'''
Multi
'''
"""

#Arithmetic operators(+,-,/,%,*,//)

x = 15.5
y = 5
Z = x + y
C = x - y
A = x/y
print(x+y)#=15+5
print(Z)
print(C)#15-5
print(A)

x = 15.5
y = 5
A = x/y
print(A)

x = 15
y = 2
A = x//y
print(A)

x = 15
y = 2
z= x*y
print(z)

x = 15
y = 2
z= x**y
print(z)

x = 15
y = 2
z= x%y
print(z)

#Assignment operators(=,+=,-=,=,/=,%=,//=,*=,&=,|=,^=,>>=,<<=)

x = 5
x +=3  #x+3=5+3=8     ---X=X+3

print(x)

x = 5
x -=3  #x-3=5-3=2     ---X=X-3

print(x)

x = 5
x *=3  #=5*3=15     ---X=X*3

print(x)

x = 5
x /=3

print(x)

x = 5
x //=3

print(x)

#Comparison operators(==,!=,>,<,>=,<=)
x= 7
y= 5
print(x == y)#True or Fale

x= 7
y= 5
print(x != y)#True or Fale

x= 7
y= 5
print(x > y)#True or False

x= 7
y= 5
print(x >= y)#True or False

x= 7
y= 5
print(x < y)#True or False

x= 7
y= 5
print(x <= y)#True or False

#Logical operators(and ,or,not)
x = 5
print(x> 3 and x<10)

x = 5
print(x> 6 or x<10)

x = 5
print(not(x> 6 or x<10))

#Identity operators(is ,is not)
x = ["apple","bananna"]
y = ["apple","bananna"]
z = x
print (x is z)#True
print(x is y)#False
print(x == y)#true

#Identity operators(is ,is not)
x = ["apple","bananna"]
y = ["apple","bananna"]
z = x
print (x is not z)#F
print(x is not y)#T
print(x != y)#F

#Membership operators(in ,not in)

x = ["apple","bananna"]
print("bananna" in x)

x = ["apple","bananna"]
print("bananna" not in x)

''''
#Bitwise operators(& -AND,
|-OR,
^-XOR,
~-NOT,
<< -Zero fill left shift,>>-Signed right shift)

'''
print(3<<2)# inc
print(8>>2)#dec

x = 5
print(x> 3 & x<10)#t

print(x> 6 | x<10)#t

#Python I/O
x = input("enter number:")
print (type(x))

x = int(input("enter number:"))
print(x)
print (type(x))

x = int(input("enter number:"))
print(x)
print (type(x))

x = float(input("enter number:"))
print(x)
print (type(x))

# raw_input()

x = int(input())
print(x)
print (type(x))#Abc

#import
import math

y = math.sqrt(25)
print(y)

import math

y = math.ceil(25.5)
x = math.floor(25.5)
print(y)
print(x)

import math as m

x = m.pi
print(x)

x =5#global
def  myfun():
  print(x)
myfun()

x =5#global
def  myfun():
  x = 4#local
  print(x)
myfun()

def  myfun():
  b = 4#local

myfun()
print(b)

def  myfun():
  global b
  b = 4

myfun()
print(b)

b = 5
def  myfun():
   b = 4
   print(b)
myfun()
print(b)

b = 5
b = 4
print(b)