# -*- coding: utf-8 -*-
"""String.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1L6xNHBZemHDkeoZXBIbC050pI6GGvNiM
"""

print("hello")
print('hello')

a = "hello"
print(a)

b = '''
In mathematics, the quaternion number system extends the complex numbers. Quaternions were first described by the Irish
mathematician William Rowan Hamilton in 1843[1][2] and applied to mechanics in three-dimensional space. Hamilton defined
a quaternion as the quotient of two directed lines in a three-dimensional space,[3] or, equivalently, as the quotient of
 two vectors.[4] Multiplication of quaternions is noncommutative.
 '''

print(b)

b = """
In mathematics, the quaternion number system extends the complex numbers. Quaternions were first described by the Irish
mathematician William Rowan Hamilton in 1843[1][2] and applied to mechanics in three-dimensional space. Hamilton defined
a quaternion as the quotient of two directed lines in a three-dimensional space,[3] or, equivalently, as the quotient of
 two vectors.[4] Multiplication of quaternions is noncommutative.
 """
print(b)

a = "hello"
print(a[1])

print(a[-1])

for x in 'apple':
  print(x)

print(len("apple"))

print(type("apple"))

text = " my name is lakshmi"
print("my" in text)

if 'my' in text:
  print("yes")

if 'my' not in text:
  print("no")

b = 'hello,world!'
print(b[6:11])

print(b[-5:-2])

print(b.upper())

print(b.lower())

print(len("  "))

b = "  hello, World!   "

print(b.strip())
print(len(b))

print(b.replace("h","J"))

a = "hello,world!"
print(a.split(","))

a = "hello"
b = 'hello'
print(a==b)

c = a + b
print(c)

c = a +" "+ b
print(c)

age = 25
text = "my name is john, i am"+age
print(text)

age = 25
text = "my name is john, i am {}"
print(text.format(age))

quantity = 3
item = 250
price = 25
myorder = " i want {} pieces of item {} for {} dollars."
print(myorder.format(quantity,item,price))

quantity = 3
item = 250
price = 25
myorder = " i want {0} pieces of item {2} for {1} dollars."
print(myorder.format(quantity,price,item))#0,1,2

print("hello\n")
print("hello")

print("hello\t",end = "*")
print("hello")

print("hello," ,"world",sep ="*")

text = "lakshmi"
x = text.capitalize()
print(x)

y = text.casefold()
print(y)

z = text.center(20)
print(z)

x= text.count("l")
print(x)

text = "hello, welcome to my world"
x = text.endswith("d")
print(x)

x = text.index("hello")
print(x)

text ="company12"
x = text.isalnum()
print(x)

text ="company"
print(text.isalpha())

X = "123"
Y = X.isdecimal()
print(Y)

str1 = "hello"
print(str1[::-1])

def count_vowels(input_string):
  vowel = "aeiouAEIOU"
  vowel_count = 0
  for char in input_string:
    if char in vowel:
      vowel_count+=1#0+1 =1--1+1=2
  return vowel_count
input_string = input("enter a string:")
result = count_vowels(input_string)
print(result)

def count_vowels(input_string):
  vowel = "aeiouAEIOU"
  vowel_count = 0
  for char in input_string:
    if char in vowel:
      vowel_count+=1#0+1 =1--1+1=2
  print(vowel_count)
count_vowels("Lakshmi")

