# -*- coding: utf-8 -*-
"""Tuples.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16An7558NoW2P99hMcbJf8u6nA3SkuNqC
"""

#list --mutable =update,remove
'''
Store-any data type
Acees
update
add
remove

'''

#usage:
'''
data storing
tasks-maximum method-max,min,sort,reverse
analyze
handle-flexible
'''

"""#=,shallow copy,deep copy"""

a = [1,2,3,4]
b = a
b[0] = 100
print("a ",a)
print("b",b)

p = [1,2,3,4]
q = p.copy()
print(p)
print(q)

q[0] = 100
print ("p", p)
print("q",q)

p = [1,2,3,4,[10,20,30]]
q = p.copy()
print(p)
print(q)

q[4][0] = 1000
print("p",p)
print("q",q)

p = [1,2,3,4,[10,20,30]]
q = p.copy()
q[3] = 99
print("p",p)
print("q",q)

p[2]  = 30
print("p",p)
print("q",q)

import copy
deep_copy = copy.deepcopy(p)
print(deep_copy)

deep_copy[4][0] = 1000
print("deep copy",deep_copy)
print("p",p)

# Tuples
mytuple = ("apple","banana","cherry")#0,1,2,3,--------   -3,-2.-1
print(mytuple)

print(type(mytuple))

print(len(mytuple))

print(mytuple[0])

print(mytuple[-1])

print(mytuple[::-1])

mytuple = ("apple","banana","cherry",1,2.5,False)
print(mytuple[2:5])

mytuple[0] = 50
print(mytuple)

del mytuple[0]
print(mytuple)

tuple1 = (1,1,1,1)
print(tuple1)

"""
Acess
Slicing
orderer
allow duplicates
add,update,remove --- do not accept

"""

#formula,values

tuple2 = (1,2,3,41)
tuple2 = (10,20,30,40)
print(tuple2)

thistuple = tuple((1,2,3,4,5))
print(thistuple)
print(type(thistuple))

y = list(thistuple)
y[1] = 1000
thistuple = tuple(y)
print(thistuple)
print(type(thistuple))

x = list(thistuple)
x.remove(5)
thistuple = tuple(x)
print(thistuple)

# un packing
(green,red,blue,yellow) = thistuple
print(green)
print(red)
print(blue)
print(yellow)

(green,red,*blue) = thistuple
print(green)
print(red)
print(blue)

for i in thistuple:
  print(i)

for i in range (len(thistuple)):
  print(thistuple[i])

i = 0
while i <len(thistuple):
  print(thistuple[i])
  i+=1

tuple1 =(1,2,3,4)
tuple2 = ("apple","banana","cherry")
tuple3 = tuple1 + tuple2
print(tuple3)

list1 = []
for i in tuple1:
  x = i + 5
  list.append(x)
print(list1)

tuple1 =(1,2,3,4)
tuple2 = tuple1 * 2
print(tuple2)

q = [1,2,3,4,5]
p = (1,2,3,q)
print(p)
print(q)

q[0] = 1000
print(p)